# Generated by Django 4.1.4 on 2022-12-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('unknown', 'unknown'), ('author', 'author'), ('administrator', 'administrator')], default='unknown', max_length=14),
        ),
    ]
